FROM node:alpine as builder

WORKDIR /app

COPY 888front/package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/build/ /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
